# Generated by Django 5.0.4 on 2024-05-03 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20200508_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(max_length=266, on_delete=django.db.models.deletion.CASCADE, to='expenses.category'),
        ),
    ]
